title: MIGAO's Blog
subtitle: ''
description: ''
keywords: null
author: MIGAO
language: en
timezone: ''
url: http://draumurvakna.github.io
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
custom_css: css/_custom.css
deploy:
  type: git
  repo: git@github.com:Draumurvakna/Draumurvakna.github.io.git
  branch: main
# OhMyLive2d:
#   enable: true
#   CDN: https://registry.npmmirror.com/oh-my-live2d/latest/files
#   option:
#     libraryUrls:
#       complete: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/complete.js
#       cubism2: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism2.js
#       cubism5: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism5.js
#     dockedPosition: left
#     mobileDisplay: true
#     models:
#       # - path: https://model.oml2d.com/cat-white/model.json
#       #   mobilePosition:
#       #     - 0
#       #     - 0
#       #   mobileScale: 0.1
#       #   mobileStageStyle:
#       #     width: 150
#       #     height: 200
#       #   motionPreloadStrategy: ALL
#       #   position:
#       #     - 0
#       #     - 0
#       #   scale: 0.2
#       #   stageStyle:
#       #     width: 350
#       #     height: 450
#       # - path: https://model.oml2d.com/cat-black/model.json
#       #   mobilePosition:
#       #     - 0
#       #     - 0
#       #   mobileScale: 0.1
#       #   mobileStageStyle:
#       #     width: 150
#       #     height: 200
#       #   motionPreloadStrategy: ALL
#       #   position:
#       #     - 0
#       #     - 0
#       #   scale: 0.2
#       #   stageStyle:
#       #     width: 350
#       #     height: 450
#       - path: https://model.oml2d.com/mai/model.json
#         mobilePosition:
#           - 25
#           - 0
#         mobileScale: 0.1
#         mobileStageStyle:
#           width: 125
#           height: 175
#         motionPreloadStrategy: ALL
#         position:
#           - 50
#           - 0
#         scale: 0.2
#         stageStyle:
#           width: 250
#           height: 350
#     parentElement: document.body
#     primaryColor: var(--btn-bg)
#     sayHello: false
#     tips:
#       style:
#         width: 230
#         height: 120
#         left: calc(50% - 20px)
#         top: '-100px'
#       mobileStyle:
#         width: 180
#         height: 80
#         left: calc(50% - 30px)
#         top: '-100px'
#       idleTips:
#         interval: 15000
#         message: |
#           function(){
#             return axios.get('https://v1.hitokoto.cn?c=i')
#               .then(function (response) {
#                 return response.data.hitokoto ;
#               })
#               .catch(function (error) {
#                 console.error(error);
#               });
#           }
aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  meting: true
  meting_cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js



lightgallery:
  js: 'https://cdn.jsdelivr.net/npm/lightgallery.js@1.4.0/dist/js/lightgallery.min.js'
  css: 'https://cdn.jsdelivr.net/npm/lightgallery.js@1.4.0/dist/css/lightgallery.min.css'
  plugins:
    lg-thumbnail.js: 'https://cdn.jsdelivr.net/npm/lg-thumbnail.js@1.2.0/dist/lg-thumbnail.min.js'
    lg-fullscreen.js: 'https://cdn.jsdelivr.net/npm/lg-fullscreen.js@1.2.0/dist/lg-fullscreen.min.js'
    lg-zoom.js: 'https://cdn.jsdelivr.net/npm/lg-zoom.js@1.3.0/dist/lg-zoom.min.js'
    lg-autoplay.js: 'https://cdn.jsdelivr.net/npm/lg-autoplay.js@1.2.0/dist/lg-autoplay.min.js'
    lg-video.js: 'https://cdn.jsdelivr.net/npm/lg-video.js@1.3.0/dist/lg-video.min.js'
    lg-hash.js: 'https://cdn.jsdelivr.net/npm/lg-hash.js@1.0.0/dist/lg-hash.min.js'
    lg-pager.js: 'https://cdn.jsdelivr.net/npm/lg-pager.js@1.0.0/dist/lg-pager.min.js'
